### ISSUE TITLE
 Add a well-maintained README file to the C folder

### ISSUE THREAD

**Issue by DevAffan** [DevAffan/AffiCodes-Hacktoberfest2024#117]
Request for Contribution:

Please add a well-maintained README file to the C folder. The README should provide clear and comprehensive information about the contents of the folder, including:

    An overview of the C projects or files contained within.
    Instructions for compiling and running the code.
    Brief explanations of the algorithms or implementations included.
    Contribution guidelines for those interested in adding to or improving the projects.

A well-structured README will greatly improve accessibility and understanding for current and future contributors. Thank you for your efforts!

**Comment by rajasurya-rjs** [comment]
i would love to solve this could you assign me

**Comment by DevAffan** [comment]
Done.
