### ISSUE TITLE
Proposal: Adding an implementation of Kadane's Algorithm in C++

### ISSUE THREAD

**Issue by Shreyashahu** [DevAffan/AffiCodes-Hacktoberfest2024#121]
Objectives :

1) Develop an implementation of Kadane's Algorithm to determine the maximum sum of contiguous subarrays.
2) Create function that effectively handle arrays with both positive and negative values.
3) Include test cases to ensure the implementation works as intended.
4) Add clear comments for ease of understanding.

**Comment by DevAffan** [comment]
Hi @Shreyashahu ,

Thank you for your interest in contributing to the project! I wanted to let you know that Kadane's Algorithm has already been implemented in the repository. However, I encourage you to enhance and modify the existing implementation with a better approach and improved clarity.

Feel free to focus on adding clear comments, refining the code, and including comprehensive test cases to ensure it handles arrays with both positive and negative values effectively.

If you are interested please let me know, I will assign it to you.

Best,
Affan Ali

**Comment by Shreyashahu** [comment]
Yeah. I can do that. You can assign it to me.

**Comment by DevAffan** [comment]
Sure, I have assigned it to you.
Thank you.
