### ISSUE TITLE
Proposal: String Hashing Algorithm with Anagrams Problems

### ISSUE THREAD

**Issue by Eshan05** [DevAffan/AffiCodes-Hacktoberfest2024#124]
I would like to contribute few competitive programming questions such as **Group Anagrams** (Leetcode 49) and others which utilize _rolling string hashing_ in C++.

1. Proper implementation of the algorithm and the solution function for each problem. I will add necessary test cases in the `main` function
2. Comments will be added for explanation of the solution and the algorithm usage in it as well as easy to understand for anyone new.
3. Other ways to solve the problem will also be mentioned for completeness

**Comment by DevAffan** [comment]
Sure @Eshan05 , I am happy to assign you this.
Thank you

**Comment by Gungunmi12** [comment]
@DevAffan can u assign it to me

**Comment by Eshan05** [comment]
> @DevAffan can u assign it to me

There's already a PR
