### ISSUE TITLE
Proposal : Adding Standard Problems in C++

### ISSUE THREAD

**Issue by abishek1740P** [DevAffan/AffiCodes-Hacktoberfest2024#134]
The Problems I'd Like to Add :

1. Best Time to Buy and Sell Stock
2. Longest Substring Without Repeating Characters
3. Reverse Linked List
4. Merge Two Sorted Lists
5. Linked List Cycle
6. Maximum Depth of Binary Tree
7. Symmetric Tree
8. Binary Tree Level Order Traversal
9. Climbing Stairs
10. Longest Increasing Subsequence
11. Coin Change
12. Permutations
13. Subsets
14. N-Queens
15. Merge Intervals

@DevAffan  Assign me this issue. With Hacktoberfest as Label .

**Comment by DevAffan** [comment]
Hi @abishek1740P,

Thank you for your interest in contributing to the repository! I’m happy to assign you this task. However, please ensure to avoid pushing duplicate algorithms or the same algorithm with a similar approach. Alternatively, you can enhance or modify the existing algorithms for greater clarity and improvement.

I appreciate your enthusiasm and look forward to seeing your contributions!

Thank you.
