### ISSUE TITLE
Alternative Sorting in cpp

### ISSUE THREAD

**Issue by TanushreeBorase** [DevAffan/AffiCodes-Hacktoberfest2024#150]
I would like to add code for alternative sorting in cpp.
Alternative Sorting: Given an array of integers, print the array in such a way that the first element is first maximum and second element is first minimum and so on.
Please assign me this issue under hacktoberfest 2024

**Comment by DevAffan** [comment]
Done. Please avoid pushing duplicate Algorithms. Alternatively, you can enhance the existing ones.
Thank you
