### ISSUE TITLE
Boyer-Moore Algorithm in Java

### ISSUE THREAD

**Issue by yashisrani** [DevAffan/AffiCodes-Hacktoberfest2024#158]
The Boyer-Moore Algorithm is a string search algorithm that scans the text from left to right but matches the pattern from right to left. It's particularly efficient for large texts and patterns since it skips sections of the text, making it faster than many other search algorithms in certain scenarios.

I want to add this algorithm code ..

**Comment by DevAffan** [comment]
Assigned.

**Comment by Gungunmi12** [comment]
I want to solve this problem
