### ISSUE TITLE
Proposal : Adding Coin change II in cpp

### ISSUE THREAD

**Issue by Amber-Mishra-2003** [DevAffan/AffiCodes-Hacktoberfest2024#163]
What I’d Like to Do:

* Given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money.

* Return the number of combinations that make up that amount. If that amount of money cannot be made up by any combination of the coins, return 0.

* You may assume that you have an infinite number of each kind of coin. 

* I will do it in cpp

**Comment by DevAffan** [comment]
Done.
