### ISSUE TITLE
Proposal: Add Leetcode Problem No.1041

### ISSUE THREAD

**Issue by iPriyanshu19** [DevAffan/AffiCodes-Hacktoberfest2024#169]
I would like to add solution of Leetcode problem No.1041 ([Robot Bounded In Circle](https://leetcode.com/problems/robot-bounded-in-circle/)) to C++ folder

**Comment by Sofiyan-coder** [comment]
Hi @iPriyanshu19 , could you please assign this issue to me? I'd love to contribute and start my open source journey with this project!
