### ISSUE TITLE
Proposal : Adding Coin change in cpp

### ISSUE THREAD

**Issue by Amber-Mishra-2003** [DevAffan/AffiCodes-Hacktoberfest2024#180]
What I’d Like to Do:

* You are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money.

* Return the fewest number of coins that you need to make up that amount. If that amount of money cannot be made up by any combination of the coins, return -1.

* You may assume that you have an infinite number of each kind of coin.

* I will do in cpp

**Comment by Pratik-k-sahoo** [comment]
Is this issue valid for hacktoberfest 2024? If valid then can you assign me ?

**Comment by DevAffan** [comment]
Hi @Pratik-k-sahoo .
It is done. You can go through the repository and find other tasks or you can open a new issue with a problem statement or suggestion that can help others in learning, I will assign that to you.

thank you
