### ISSUE TITLE
readme can be improved with steps of contribution and content

### ISSUE THREAD

**Issue by kanikaa-3018** [DevAffan/AffiCodes-Hacktoberfest2024#65]
please assign me this issue for hacktoberfest24, im willing to do this

**Comment by DevAffan** [comment]
Hi Kanika, I'm happy to see your interest in improving the Readme, Hope this will be beneficial for others as well.
Thank you

**Comment by adityakalburgi** [comment]
HI! @DevAffan  can you assign this issue to me?

**Comment by kanikaa-3018** [comment]
hey @DevAffan , there is some issue for sending the pr
