### ISSUE TITLE
Longest Increasing Subsequence (LIS)

### ISSUE THREAD

**Issue by Astordnomer** [DevAffan/AffiCodes-Hacktoberfest2024#75]
can you assign so i create Longest Increasing Subsequence (LIS) using cpp with code explanation

**Comment by DevAffan** [comment]
Sure, I assigned it to you.
Thank you.

**Comment by rajasurya-rjs** [comment]
hey i am also intrested in this can you assign me

**Comment by DevAffan** [comment]
Hi @rajasurya-rjs,

Thank you for your interest in contributing! However, @Astordnomer is already working on the implementation in C++. If you would like to contribute by adding the algorithm in another programming language, please let me know, and I would be happy to assign this issue to you as well.

**Comment by Astordnomer** [comment]
i complete this
