### ISSUE TITLE
Add Binary Search in java

### ISSUE THREAD

**Issue by harshit1142** [DevAffan/AffiCodes-Hacktoberfest2024#78]
Addition of Binary Search code in java. Can you assign me this issue?

**Comment by DevAffan** [comment]
Done.

**Comment by SourabhRajput123** [comment]
Hi,

Could you assign this issue to me as well? I'm a beginner and would love to contribute by adding a binary search implementation in Java. It would be a great learning opportunity for me. 

Thank you!

**Comment by DevAffan** [comment]
Thank you for the contributions, This issue is resolved in Java by @SourabhRajput123 and @harshit1142 .

**Comment by DevAffan** [comment]
Thank you, Closed
