### ISSUE TITLE
Proposal: Add BFS and DFS Implementations in Java

### ISSUE THREAD

**Issue by MihirSaiDudekula** [DevAffan/AffiCodes-Hacktoberfest2024#87]
I would like to propose adding Breadth-First Search (BFS) and Depth-First Search (DFS) graph traversal implementations in Java to the repository.
Could you please assign me this task under Hacktoberfest? Thank you!

**Comment by DevAffan** [comment]
Sure Please, I have assigned it to you, thank you.

**Comment by MihirSaiDudekula** [comment]
Hi,

I just wanted to let you know that I've created a pull request for the BFS and DFS implementations in Java. You can review it [here](https://github.com/DevAffan/AffiCodes-Hacktoberfest2024/pull/92#issue-2558269135)

Thank you.
